name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Build
        run: dotnet build ThetaNexus/ThetaNexus.csproj -c Release

      - name: Publish single file
        run: dotnet publish ThetaNexus/ThetaNexus.csproj -p:PublishProfile=SingleFile

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: ThetaNexus-win-x64
          path: publish/ThetaNexus.exe
